import { User, Contact, Business, Product, Service, Conversation, Message, Inquiry, StaffMember, ReportItem } from '../domain/types';

export const CURRENT_USER: User = {
  id: 'usr_me',
  name: 'Ajit Sharma',
  phoneNumber: '+91 98250 12345',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Everyday shopper & business owner in Rajkot',
  language: 'en',
  role: 'customer',
  ownedBusinessIds: ['biz_abc_furn'],
  staffAtBusinessIds: ['biz_abc_furn'],
  blockedUserIds: [],
  blockedBusinessIds: [],
};

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cnt_raj_patel',
    name: 'Raj Patel',
    phoneNumber: '+91 98251 44321',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    statusMessage: 'Available for work',
    hasApp: true,
  },
  {
    id: 'cnt_rajesh_shah',
    name: 'Rajesh Shah',
    phoneNumber: '+91 98252 88712',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    statusMessage: 'In a meeting',
    hasApp: true,
  },
  {
    id: 'cnt_rahul',
    name: 'Rahul',
    phoneNumber: '+91 98253 99120',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    statusMessage: 'Hey there! I am using Sampark.',
    hasApp: true,
  },
  {
    id: 'cnt_neha',
    name: 'Neha',
    phoneNumber: '+91 98254 33211',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    statusMessage: 'Busy right now',
    hasApp: true,
  },
  {
    id: 'cnt_priya',
    name: 'Priya Mehta',
    phoneNumber: '+91 98255 77123',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    statusMessage: 'Architecture & Interiors',
    hasApp: true,
  },
];

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 'biz_abc_furn',
    ownerId: 'usr_me',
    name: 'ABC Furniture',
    category: 'Furniture Store',
    subcategory: 'Home & Office Furniture',
    businessType: 'physical_store',
    description: 'Premier manufacturer and retailer of handcrafted wooden furniture, modular sofas, and customized dining sets in Rajkot.',
    phone: '+91 98250 88990',
    email: 'contact@abcfurniture.in',
    address: 'Plot 42, Gondal Road, Near Samrat Industrial Area',
    city: 'Rajkot',
    lat: 22.2856,
    lng: 70.7932,
    coverImageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=200&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewCount: 128,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sat',
      openTime: '09:00',
      closeTime: '20:00',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 12,
      responseRatePct: 94,
      text: 'Usually replies within 15 minutes',
    },
    verification: {
      level: 2,
      mobileVerified: true,
      mobileVerifiedAt: '2026-08-10',
      locationVerified: true,
      locationVerifiedAt: '2026-08-12',
      verifiedCoordinates: {
        lat: 22.2856,
        lng: 70.7932,
        accuracyMeters: 8,
        address: 'Plot 42, Gondal Road, Rajkot',
      },
      businessDocVerified: false,
      lastVerifiedDate: '2026-08-12',
      reverificationRequired: false,
    },
    subscriptionTier: 'free',
    activeConversationsCount: 4,
    maxActiveConversations: 10,
    greetingMessage: 'Welcome to ABC Furniture! How can we help you furnish your space today?',
    awayMessage: 'We are currently closed for the day. Our team will reply promptly when we open at 9:00 AM.',
    quickReplies: [
      'Yes, customization is available in all fabrics.',
      'We offer free delivery across Rajkot.',
      'Our showroom is open Monday to Saturday from 9 AM to 8 PM.',
    ],
    searchKeywords: ['abc', 'furniture', 'sofa', 'wood', 'bed', 'dining table', 'rajkot', 'interior'],
  },
  {
    id: 'biz_raj_hard',
    ownerId: 'usr_rajesh_owner',
    name: 'Raj Hardware',
    category: 'Hardware Store',
    subcategory: 'Tools & Construction Fittings',
    businessType: 'physical_store',
    description: 'Wholesale and retail distributor of industrial power tools, architectural brass fittings, locks, and hardware fasteners.',
    phone: '+91 98251 77334',
    address: 'Shop 12, Dhebar Road Hardware Market',
    city: 'Rajkot',
    lat: 22.2980,
    lng: 70.8010,
    coverImageUrl: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=200&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewCount: 92,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sat',
      openTime: '08:30',
      closeTime: '20:30',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 8,
      responseRatePct: 98,
      text: 'Usually replies within 10 minutes',
    },
    verification: {
      level: 3,
      mobileVerified: true,
      mobileVerifiedAt: '2026-07-15',
      locationVerified: true,
      locationVerifiedAt: '2026-07-16',
      verifiedCoordinates: {
        lat: 22.2980,
        lng: 70.8010,
        accuracyMeters: 6,
        address: 'Shop 12, Dhebar Road, Rajkot',
      },
      businessDocVerified: true,
      businessDocType: 'gstin',
      businessDocNumber: '24AAACR1234F1Z8',
      businessDocVerifiedAt: '2026-07-20',
      lastVerifiedDate: '2026-07-20',
      reverificationRequired: false,
    },
    subscriptionTier: 'starter',
    activeConversationsCount: 14,
    maxActiveConversations: 9999,
    greetingMessage: 'Namaste! Welcome to Raj Hardware. How can we assist with your tools & fittings requirements?',
    quickReplies: [
      'Yes, GST invoice will be provided.',
      'We have bulk contractor pricing available.',
      'Genuine manufacturer warranty included on all power tools.',
    ],
    searchKeywords: ['raj', 'hardware', 'tools', 'drill', 'locks', 'screws', 'fittings', 'rajkot'],
  },
  {
    id: 'biz_rajkamal_timber',
    ownerId: 'usr_rajkamal',
    name: 'Rajkamal Timber',
    category: 'Timber & Plywood',
    subcategory: 'Building Materials',
    businessType: 'physical_store',
    description: 'Importers and stockists of Burma Teak, African Teak, Marine Grade Plywood, and decorative laminates.',
    phone: '+91 98252 66554',
    address: 'Near Aji Dam GIDC, Phase II',
    city: 'Rajkot',
    lat: 22.2689,
    lng: 70.8245,
    coverImageUrl: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=200&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 45,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sat',
      openTime: '09:00',
      closeTime: '19:30',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 20,
      responseRatePct: 91,
      text: 'Usually replies within 30 minutes',
    },
    verification: {
      level: 2,
      mobileVerified: true,
      mobileVerifiedAt: '2026-08-01',
      locationVerified: true,
      locationVerifiedAt: '2026-08-02',
      businessDocVerified: false,
      lastVerifiedDate: '2026-08-02',
      reverificationRequired: false,
    },
    subscriptionTier: 'free',
    activeConversationsCount: 5,
    maxActiveConversations: 10,
    searchKeywords: ['raj', 'rajkamal', 'timber', 'plywood', 'teak', 'wood', 'laminates', 'rajkot'],
  },
  {
    id: 'biz_raj_furn',
    ownerId: 'usr_raj_f',
    name: 'Raj Furniture',
    category: 'Furniture',
    subcategory: 'Furniture Manufacturer',
    businessType: 'manufacturer',
    description: 'Specialized manufacturing unit for ergonomic office chairs, modular executive desks, and metal storage solutions.',
    phone: '+91 98253 44556',
    address: 'Atika Industrial Area, Dhebar South',
    city: 'Rajkot',
    lat: 22.2740,
    lng: 70.7980,
    coverImageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewCount: 38,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sat',
      openTime: '09:30',
      closeTime: '19:00',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 25,
      responseRatePct: 88,
      text: 'Usually replies within an hour',
    },
    verification: {
      level: 1,
      mobileVerified: true,
      mobileVerifiedAt: '2026-09-01',
      locationVerified: false,
      businessDocVerified: false,
      lastVerifiedDate: '2026-09-01',
      reverificationRequired: false,
    },
    subscriptionTier: 'free',
    activeConversationsCount: 3,
    maxActiveConversations: 10,
    searchKeywords: ['raj', 'furniture', 'office', 'chairs', 'desks', 'manufacturer', 'rajkot'],
  },
  {
    id: 'biz_synnera',
    ownerId: 'usr_synnera',
    name: 'Synnera Mattress',
    category: 'Mattress & Bedding',
    subcategory: 'Sleep Solutions',
    businessType: 'physical_store',
    description: 'Certified orthopedic and pocket spring mattress brand delivering customized comfort directly from our factory studio.',
    phone: '+91 98254 11223',
    address: '150 Feet Ring Road, Near Indira Circle',
    city: 'Rajkot',
    lat: 22.3012,
    lng: 70.7812,
    coverImageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=200&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 164,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sun',
      openTime: '10:00',
      closeTime: '21:00',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 10,
      responseRatePct: 96,
      text: 'Usually replies within 15 minutes',
    },
    verification: {
      level: 3,
      mobileVerified: true,
      locationVerified: true,
      businessDocVerified: true,
      businessDocType: 'gstin',
      businessDocNumber: '24AAACS9988G1ZK',
      lastVerifiedDate: '2026-09-10',
      reverificationRequired: false,
    },
    subscriptionTier: 'growth',
    activeConversationsCount: 18,
    maxActiveConversations: 9999,
    greetingMessage: 'Hello! Thank you for contacting Synnera Mattress. How can we help you choose the right mattress?',
    quickReplies: [
      'We offer a 10-year warranty on all pocket spring mattresses.',
      'Custom dimensions can be manufactured in 48 hours.',
      'Free doorstep trial available at our 150ft Ring Road experience center.',
    ],
    searchKeywords: ['synnera', 'mattress', 'bed', 'sleep', 'pocket spring', 'orthopedic', 'pillow', 'rajkot'],
  },
  {
    id: 'biz_modern_furn',
    ownerId: 'usr_modern',
    name: 'Modern Furniture',
    category: 'Furniture Store',
    subcategory: 'Interior & Decor',
    businessType: 'physical_store',
    description: 'Contemporary European designs, luxury recliners, and modern lifestyle furniture.',
    phone: '+91 98255 00998',
    address: 'Kalawad Road, Opposite Crystal Mall',
    city: 'Rajkot',
    lat: 22.2811,
    lng: 70.7699,
    coverImageUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=200&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewCount: 76,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sun',
      openTime: '10:00',
      closeTime: '21:00',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 18,
      responseRatePct: 90,
      text: 'Usually replies within 20 minutes',
    },
    verification: {
      level: 2,
      mobileVerified: true,
      locationVerified: true,
      businessDocVerified: false,
      lastVerifiedDate: '2026-08-20',
      reverificationRequired: false,
    },
    subscriptionTier: 'free',
    activeConversationsCount: 6,
    maxActiveConversations: 10,
    searchKeywords: ['modern', 'furniture', 'interior', 'recliner', 'luxury', 'sofa', 'rajkot'],
  },
  {
    id: 'biz_abc_ac_service',
    ownerId: 'usr_abc_service',
    name: 'ABC Services',
    category: 'Home Service',
    subcategory: 'AC Repair & Electrical',
    businessType: 'home_service',
    description: 'Professional doorstep air conditioner installation, gas charging, jet pump chemical cleaning, and electrical repairs.',
    phone: '+91 98256 55443',
    address: 'Mobile Service (Covering all of Rajkot city & outskirts)',
    city: 'Rajkot',
    lat: 22.3000,
    lng: 70.8000,
    coverImageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&auto=format&fit=crop&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=200&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewCount: 210,
    openForChat: true,
    businessHours: {
      days: 'Mon - Sun',
      openTime: '08:00',
      closeTime: '20:00',
      isOpenToday: true,
    },
    responseMetrics: {
      avgResponseMinutes: 5,
      responseRatePct: 99,
      text: 'Usually replies within 5 minutes',
    },
    verification: {
      level: 2,
      mobileVerified: true,
      locationVerified: true,
      businessDocVerified: false,
      lastVerifiedDate: '2026-09-15',
      reverificationRequired: false,
    },
    subscriptionTier: 'starter',
    activeConversationsCount: 8,
    maxActiveConversations: 9999,
    greetingMessage: 'ABC Services at your doorstep! Which appliance requires servicing today?',
    quickReplies: [
      'Technician can reach within 90 minutes anywhere in Rajkot.',
      'Standard inspection fee is ₹150, waived if repair completed.',
    ],
    searchKeywords: ['abc', 'ac', 'repair', 'service', 'technician', 'electrician', 'cleaning', 'rajkot'],
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_pocket_mattress',
    businessId: 'biz_synnera',
    businessName: 'Synnera Mattress',
    name: 'Pocket Spring Mattress (72x78)',
    description: 'Zero motion transfer pocket spring mattress with high-density breathable Euro-top padding. Ideal for orthopaedic spinal alignment.',
    category: 'Mattress',
    price: 12500,
    priceOnRequest: false,
    sku: 'SYN-PS-7278',
    imageUrl: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['mattress', 'pocket spring', 'bed', 'synnera', 'spring', 'sleep', '72x78'],
  },
  {
    id: 'prod_ortho_mattress',
    businessId: 'biz_synnera',
    businessName: 'Synnera Mattress',
    name: 'Orthopedic Memory Foam Mattress',
    description: 'Pressure-relieving memory foam engineered with cool gel technology for hot climates. 10-year replacement warranty.',
    category: 'Mattress',
    price: 15800,
    priceOnRequest: false,
    sku: 'SYN-ORTHO-01',
    imageUrl: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['mattress', 'orthopedic', 'memory foam', 'synnera', 'bed'],
  },
  {
    id: 'prod_sofa_3seater',
    businessId: 'biz_abc_furn',
    businessName: 'ABC Furniture',
    name: '3-Seater Chesterfield Fabric Sofa',
    description: 'Hand-tufted premium suede finish sofa built with treated teak internal framing and 40-density high resilience foam.',
    category: 'Furniture',
    price: 24500,
    priceOnRequest: false,
    sku: 'ABC-SOFA-3S',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['sofa', '3 seater', 'couch', 'chesterfield', 'furniture', 'abc furniture'],
  },
  {
    id: 'prod_dining_table',
    businessId: 'biz_abc_furn',
    businessName: 'ABC Furniture',
    name: 'Solid Teak 6-Seater Dining Table',
    description: 'Natural wood grain polished dining table with 6 ergonomically cushioned chairs. Termite and borer resistant.',
    category: 'Furniture',
    price: 32000,
    priceOnRequest: false,
    sku: 'ABC-DINE-06',
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['dining table', 'table', 'chairs', 'teak wood', 'furniture', 'abc furniture'],
  },
  {
    id: 'prod_king_bed',
    businessId: 'biz_abc_furn',
    businessName: 'ABC Furniture',
    name: 'King Size Hydraulic Storage Bed',
    description: 'Effortless hydraulic lift storage with plush upholstered headboard. Fits standard 72x78 mattress.',
    category: 'Furniture',
    price: 28500,
    priceOnRequest: false,
    sku: 'ABC-BED-KNG',
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['bed', 'king bed', 'hydraulic storage', 'furniture', 'abc furniture'],
  },
  {
    id: 'prod_hardware_tools',
    businessId: 'biz_raj_hard',
    businessName: 'Raj Hardware',
    name: 'Hardware Tools & Rotary Drill Kit',
    description: 'Heavy duty 850W rotary hammer drill with 26-piece masonry drill bits, anchor set, and rugged toolbox.',
    category: 'Hardware',
    price: 4850,
    priceOnRequest: false,
    sku: 'RAJ-TOOL-KIT',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['hardware tools', 'tools', 'drill', 'raj hardware', 'machinery'],
  },
  {
    id: 'prod_brass_locks',
    businessId: 'biz_raj_hard',
    businessName: 'Raj Hardware',
    name: 'Heavy Duty Solid Brass Padlock (65mm)',
    description: 'Anti-cut hardened steel shackle with double locking brass cylinder. 4 computerised dimple keys included.',
    category: 'Hardware',
    price: 650,
    priceOnRequest: false,
    sku: 'RAJ-LCK-65',
    imageUrl: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['padlock', 'locks', 'brass', 'hardware', 'raj hardware'],
  },
  {
    id: 'prod_teak_timber',
    businessId: 'biz_rajkamal_timber',
    businessName: 'Rajkamal Timber',
    name: 'Teak Timber & Cut Wood Planks',
    description: 'Seasoned Burma and Ghana Teak timber logs and cut-to-size beams. Kiln dried with guaranteed low moisture content.',
    category: 'Timber',
    price: 0,
    priceOnRequest: true,
    sku: 'RKT-TEAK-LOGS',
    imageUrl: 'https://images.unsplash.com/photo-1546484396-fb3fc6f95f98?w=600&auto=format&fit=crop&q=80',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['teak timber', 'timber', 'wood', 'plywood', 'rajkamal timber'],
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv_ac_repair',
    businessId: 'biz_abc_ac_service',
    businessName: 'ABC Services',
    name: 'AC Repair & Jet Servicing',
    description: 'Comprehensive high-pressure jet pump cleaning of indoor coil, outdoor condenser, filter replacement, and gas pressure check.',
    category: 'Appliance Repair',
    startingPrice: 500,
    serviceArea: 'All Rajkot areas within 20km',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['ac repair', 'ac', 'servicing', 'cooling', 'cleaning', 'abc services'],
  },
  {
    id: 'srv_custom_furniture',
    businessId: 'biz_abc_furn',
    businessName: 'ABC Furniture',
    name: 'Custom Furniture Making',
    description: 'Bespoke design and fabrication of wardrobes, TV units, and sofas according to your room floorplan and color palette.',
    category: 'Carpentry & Design',
    startingPrice: 5000,
    serviceArea: 'Rajkot and Saurashtra region',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['custom furniture', 'carpenter', 'wardrobe', 'sofa', 'abc furniture'],
  },
  {
    id: 'srv_furniture_repair',
    businessId: 'biz_abc_furn',
    businessName: 'ABC Furniture',
    name: 'Furniture Repair & Polishing',
    description: 'PU and Melamine spray polishing, sofa foam restructuring, fabric change, and structural wooden joint restoration.',
    category: 'Restoration',
    startingPrice: 1200,
    serviceArea: 'Rajkot City',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['furniture repair', 'polishing', 'sofa repair', 'abc furniture'],
  },
  {
    id: 'srv_hardware_installation',
    businessId: 'biz_raj_hard',
    businessName: 'Raj Hardware',
    name: 'Hardware Installation & Fitting',
    description: 'On-site installation for digital door locks, glass door hinges, telescopic drawer slides, and architectural handles.',
    category: 'Installation',
    startingPrice: 350,
    serviceArea: 'Rajkot City',
    available: true,
    location: 'Rajkot',
    searchKeywords: ['hardware installation', 'fitting', 'lock installation', 'raj hardware'],
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_raj_patel',
    type: 'direct',
    participantIds: ['usr_me', 'cnt_raj_patel'],
    otherParticipant: {
      id: 'cnt_raj_patel',
      name: 'Raj Patel',
      phoneNumber: '+91 98251 44321',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    },
    lastMessage: {
      text: 'Send me the quotation',
      senderId: 'cnt_raj_patel',
      timestamp: '10:42 AM',
      type: 'text',
    },
    unreadCount: 1,
    updatedAt: '2026-10-04T10:42:00Z',
  },
  {
    id: 'conv_abc_furn',
    type: 'business',
    participantIds: ['usr_me', 'biz_abc_furn'],
    businessId: 'biz_abc_furn',
    otherParticipant: {
      id: 'biz_abc_furn',
      name: 'ABC Furniture',
      avatarUrl: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=200&auto=format&fit=crop&q=80',
      phoneNumber: '+91 98250 88990',
      isBusiness: true,
      businessId: 'biz_abc_furn',
      verification: INITIAL_BUSINESSES[0].verification,
      openForChat: true,
    },
    lastMessage: {
      text: 'Your sofa is ready',
      senderId: 'biz_abc_furn',
      timestamp: '09:15 AM',
      type: 'text',
    },
    unreadCount: 0,
    updatedAt: '2026-10-04T09:15:00Z',
  },
  {
    id: 'conv_rahul',
    type: 'direct',
    participantIds: ['usr_me', 'cnt_rahul'],
    otherParticipant: {
      id: 'cnt_rahul',
      name: 'Rahul',
      phoneNumber: '+91 98253 99120',
      avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    },
    lastMessage: {
      text: 'Okay, tomorrow',
      senderId: 'usr_me',
      timestamp: 'Yesterday',
      type: 'text',
      status: 'read',
    },
    unreadCount: 0,
    updatedAt: '2026-10-03T18:20:00Z',
  },
  {
    id: 'conv_neha',
    type: 'direct',
    participantIds: ['usr_me', 'cnt_neha'],
    otherParticipant: {
      id: 'cnt_neha',
      name: 'Neha',
      phoneNumber: '+91 98254 33211',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    lastMessage: {
      text: 'Thank you',
      senderId: 'cnt_neha',
      timestamp: 'Friday',
      type: 'text',
    },
    unreadCount: 0,
    updatedAt: '2026-10-02T14:10:00Z',
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  conv_raj_patel: [
    {
      id: 'msg_rp_1',
      conversationId: 'conv_raj_patel',
      senderId: 'usr_me',
      senderName: 'Ajit Sharma',
      type: 'text',
      text: 'Hey Raj, did you inspect the site drawings?',
      timestamp: '10:30 AM',
      status: 'read',
    },
    {
      id: 'msg_rp_2',
      conversationId: 'conv_raj_patel',
      senderId: 'cnt_raj_patel',
      senderName: 'Raj Patel',
      type: 'text',
      text: 'Yes, looking good. Finalising the material requirements.',
      timestamp: '10:35 AM',
      status: 'read',
    },
    {
      id: 'msg_rp_3',
      conversationId: 'conv_raj_patel',
      senderId: 'cnt_raj_patel',
      senderName: 'Raj Patel',
      type: 'text',
      text: 'Send me the quotation',
      timestamp: '10:42 AM',
      status: 'delivered',
    },
  ],
  conv_abc_furn: [
    {
      id: 'msg_abc_0',
      conversationId: 'conv_abc_furn',
      senderId: 'biz_abc_furn',
      senderName: 'ABC Furniture',
      type: 'text',
      text: 'Welcome to ABC Furniture. How can we help you?',
      timestamp: 'Yesterday 11:00 AM',
      status: 'read',
    },
    {
      id: 'msg_abc_1',
      conversationId: 'conv_abc_furn',
      senderId: 'usr_me',
      senderName: 'Ajit Sharma',
      type: 'product_card',
      text: 'I am interested in 3-Seater Chesterfield Fabric Sofa.',
      productRef: {
        id: 'prod_sofa_3seater',
        name: '3-Seater Chesterfield Fabric Sofa',
        price: 24500,
        imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
      },
      timestamp: 'Yesterday 11:05 AM',
      status: 'read',
    },
    {
      id: 'msg_abc_2',
      conversationId: 'conv_abc_furn',
      senderId: 'biz_abc_furn',
      senderName: 'ABC Furniture',
      type: 'text',
      text: 'Your sofa is ready',
      timestamp: '09:15 AM',
      status: 'read',
    },
  ],
  conv_rahul: [
    {
      id: 'msg_rh_1',
      conversationId: 'conv_rahul',
      senderId: 'cnt_rahul',
      senderName: 'Rahul',
      type: 'text',
      text: 'Are we meeting at the store today?',
      timestamp: 'Yesterday 18:15',
      status: 'read',
    },
    {
      id: 'msg_rh_2',
      conversationId: 'conv_rahul',
      senderId: 'usr_me',
      senderName: 'Ajit Sharma',
      type: 'text',
      text: 'Okay, tomorrow',
      timestamp: 'Yesterday 18:20',
      status: 'read',
    },
  ],
  conv_neha: [
    {
      id: 'msg_nh_1',
      conversationId: 'conv_neha',
      senderId: 'usr_me',
      senderName: 'Ajit Sharma',
      type: 'text',
      text: 'Sent the documents across.',
      timestamp: 'Friday 14:00',
      status: 'read',
    },
    {
      id: 'msg_nh_2',
      conversationId: 'conv_neha',
      senderId: 'cnt_neha',
      senderName: 'Neha',
      type: 'text',
      text: 'Thank you',
      timestamp: 'Friday 14:10',
      status: 'read',
    },
  ],
};

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq_1',
    businessId: 'biz_abc_furn',
    businessName: 'ABC Furniture',
    customerId: 'usr_me',
    customerName: 'Ajit Sharma',
    conversationId: 'conv_abc_furn',
    entityType: 'product',
    entityId: 'prod_sofa_3seater',
    entityTitle: '3-Seater Chesterfield Fabric Sofa',
    requirementNote: 'Wants navy blue suede finish with matching throw cushions.',
    status: 'quotation_sent',
    assignedStaffId: 'stf_rahul',
    assignedStaffName: 'Rahul (Sales)',
    createdAt: '2026-10-03T11:05:00Z',
    updatedAt: '2026-10-04T09:15:00Z',
  },
  {
    id: 'inq_2',
    businessId: 'biz_synnera',
    businessName: 'Synnera Mattress',
    customerId: 'usr_me',
    customerName: 'Ajit Sharma',
    conversationId: 'conv_synnera_temp',
    entityType: 'product',
    entityId: 'prod_pocket_mattress',
    entityTitle: 'Pocket Spring Mattress (72x78)',
    requirementNote: 'Needs delivery to Gondal Road apartment with unboxing service.',
    status: 'new',
    createdAt: '2026-10-04T08:00:00Z',
    updatedAt: '2026-10-04T08:00:00Z',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'stf_owner',
    businessId: 'biz_abc_furn',
    userId: 'usr_me',
    name: 'Ajit Sharma (Owner)',
    role: 'owner',
    phoneNumber: '+91 98250 12345',
    assignedCount: 1,
  },
  {
    id: 'stf_rahul',
    businessId: 'biz_abc_furn',
    userId: 'usr_rahul_staff',
    name: 'Rahul Varma',
    role: 'sales',
    phoneNumber: '+91 98259 11002',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    assignedCount: 3,
  },
  {
    id: 'stf_priya',
    businessId: 'biz_abc_furn',
    userId: 'usr_priya_staff',
    name: 'Priya Joshi',
    role: 'support',
    phoneNumber: '+91 98259 33441',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    assignedCount: 2,
  },
];

export const INITIAL_REPORTS: ReportItem[] = [
  {
    id: 'rep_1',
    reporterId: 'usr_me',
    targetType: 'business',
    targetId: 'biz_fake_sample',
    targetName: 'Kalyan Traders Unverified',
    reason: 'wrong_location',
    notes: 'Shop does not exist at the specified address on Tagore Road.',
    timestamp: '2026-10-01T12:00:00Z',
    status: 'pending',
  }
];
